(function(){
  const BASE_SCRIPT="js/script-base.js";
  const CUSTOM_SCRIPT="js/product-configurator.js";
  const FIX_SCRIPT="js/fresatto-configurator-fix.js";
  const ASSET_VERSION="20260918-15";
  const OPEN_HOUR=10;
  const CLOSE_HOUR=22;
  const FRESATTO_NAME="Fresatto";
  const FRESATTO_ID="3";
  const FRESATTO_OPEN_HOUR=2;
  const FRESATTO_CLOSE_HOUR=24;
  const FRESATTO_SCHEDULE_TEXT="2:00 a. m. – 12:00 a. m.";
  function isRestaurantOpenNow(){const now=new Date(),day=now.getDay(),hour=now.getHours()+now.getMinutes()/60;return day!==0&&hour>=OPEN_HOUR&&hour<CLOSE_HOUR;}
  function isFresattoCard(card){const text=String(card?.textContent||"").toLocaleLowerCase("es"),id=String(card?.dataset?.restaurantId||card?.querySelector('[data-restaurant-id]')?.dataset?.restaurantId||"").trim(),number=String(card?.querySelector('.restaurant-number')?.textContent||'').trim();return text.includes(FRESATTO_NAME.toLocaleLowerCase("es"))||number==='03'||id===FRESATTO_ID;}
  function isFresattoMenu(){const name=String(window.currentRestaurant?.name||"").toLocaleLowerCase("es"),id=new URLSearchParams(window.location.search).get("id");return name===FRESATTO_NAME.toLocaleLowerCase("es")||String(id||"")===FRESATTO_ID;}
  function isFresattoOpenNow(){const now=new Date(),hour=now.getHours()+now.getMinutes()/60;return hour>=FRESATTO_OPEN_HOUR&&hour<FRESATTO_CLOSE_HOUR;}
  function closedLabel(){return '<span class="closed-badge">Cerrado ahora</span>';}
  function patchFresattoSchedule(){document.querySelectorAll('.restaurant-card').forEach(card=>{if(!isFresattoCard(card))return;const time=card.querySelector('.restaurant-schedule-time');if(time&&time.textContent!==FRESATTO_SCHEDULE_TEXT)time.textContent=FRESATTO_SCHEDULE_TEXT;card.querySelectorAll('.schedule-day').forEach(day=>{day.classList.remove('closed');day.classList.add('open');const title=`${day.textContent.trim()}: ${FRESATTO_SCHEDULE_TEXT}`;if(day.title!==title)day.title=title;});const close=card.querySelector('.restaurant-schedule-closed'),closeText='<strong>Horario:</strong> 2:00 a. m. – 12:00 a. m.';if(close&&close.innerHTML!==closeText)close.innerHTML=closeText;});}
  function applyClosedState(){const globalOpen=isRestaurantOpenNow(),fresattoOpen=isFresattoOpenNow();document.querySelectorAll('.restaurant-card').forEach(card=>{const button=card.querySelector('.restaurant-name-button');if(!button)return;const open=isFresattoCard(card)?fresattoOpen:globalOpen;card.classList.toggle('is-closed',!open);button.classList.toggle('is-closed',!open);button.disabled=!open;button.setAttribute('aria-disabled',String(!open));if(!open){button.setAttribute('title','Este restaurante está cerrado');if(!card.querySelector('.closed-badge')){const number=card.querySelector('.restaurant-number');if(number)number.insertAdjacentHTML('afterend',closedLabel());}}else{button.removeAttribute('title');card.querySelector('.closed-badge')?.remove();}});document.querySelectorAll('.restaurant-order-card').forEach(card=>{const open=isFresattoCard(card)?fresattoOpen:globalOpen;card.classList.toggle('is-closed',!open);card.disabled=!open;card.setAttribute('aria-disabled',String(!open));if(!open)card.setAttribute('title','Este restaurante está cerrado');else card.removeAttribute('title');});document.querySelectorAll('.menu-add').forEach(button=>{if(button.dataset.closedBaseLabel===undefined)button.dataset.closedBaseLabel=button.textContent.trim();const open=isFresattoMenu()?fresattoOpen:globalOpen;button.disabled=!open;if(!open){button.textContent='Restaurante cerrado';button.setAttribute('title','Este restaurante está cerrado');}else{button.textContent=button.dataset.closedBaseLabel;button.removeAttribute('title');}});patchFresattoSchedule();}
  function renderDirectoryFallback(filter=""){const grid=document.getElementById("restaurantGrid"),restaurants=Array.isArray(window.RESTAURANT_DIRECTORY)?window.RESTAURANT_DIRECTORY:[];if(!grid||!restaurants.length)return;const term=String(filter||"").trim().toLocaleLowerCase("es"),list=restaurants.filter(r=>String(r.name||"").toLocaleLowerCase("es").includes(term)),count=document.getElementById("restaurantCount");if(count)count.textContent=`${list.length} restaurante${list.length===1?"":"s"}`;const schedule=window.RESTAURANT_DIRECTORY_SCHEDULE,scheduleHtml=schedule?`<div class="restaurant-schedule" aria-label="Horario de atención"><div class="restaurant-schedule-title"><span>Horario</span><span class="restaurant-schedule-time">${schedule.open} – ${schedule.close}</span></div><div class="schedule-days" aria-label="Días de servicio">${(schedule.days||[]).map(day=>`<span class="schedule-day ${day.open?"open":"closed"}" title="${day.name}: ${day.open?`${schedule.open} – ${schedule.close}`:"Cerrado"}">${day.label}</span>`).join("")}</div><p class="restaurant-schedule-closed"><strong>Cierre:</strong> ${(schedule.closedDays||[]).join(", ")}</p></div>`:"";if(!list.length){grid.innerHTML=`<div class="empty-cart restaurant-empty" style="grid-column:1/-1">No encontramos ese restaurante.</div>`;return;}const safe=value=>{const div=document.createElement("div");div.textContent=value==null?"":String(value);return div.innerHTML;};grid.innerHTML=list.map((r,index)=>{const logo=String(r.id)==="3"?`<img class="fresatto-card-logo" src="assets/images/fresatto-logo-clean.svg?v=${ASSET_VERSION}" alt="Logo de Fresatto" width="150" height="150" decoding="async">`:"";return `<article class="restaurant-card reveal" data-restaurant-id="${String(r.id)}" style="animation-delay:${Math.min(index*.025,.35)}s"><div><span class="restaurant-number">${String(r.id).padStart(2,"0")}</span></div>${logo}<button class="restaurant-name-button" type="button" onclick="window.location.href='restaurante.html?id=${encodeURIComponent(r.id)}'"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3v7M3.5 3v5a2.5 2.5 0 0 0 5 0V3M6 10.5V21M17 3v18M17 3c2.2 1.7 3.5 4.2 3.5 7v1H17"/></svg><span>${safe(r.name)}</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13M13 6l6 6-6 6"/></svg></button>${scheduleHtml}</article>`;}).join("");applyClosedState();}
  function initRestaurantsFallback(){const grid=document.getElementById("restaurantGrid");if(!grid||!Array.isArray(window.RESTAURANT_DIRECTORY))return;if(!grid.children.length)renderDirectoryFallback();const search=document.getElementById("restaurantSearch");if(search&&!search.dataset.directoryFallbackBound){search.dataset.directoryFallbackBound="1";search.addEventListener("input",e=>renderDirectoryFallback(e.target.value));}patchFresattoSchedule();}
  function startClosedState(){const run=()=>{applyClosedState();setInterval(applyClosedState,30000);};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();}
  function loadFresattoVisualStyle(){if(document.getElementById("fresattoVisualMenuStyles"))return;const style=document.createElement("style");style.id="fresattoVisualMenuStyles";style.textContent=`
    .menu-page.fresatto-visual-menu .menu-grid .menu-item{position:relative;overflow:hidden;isolation:isolate;min-height:214px;background:#0d0d0d;border-color:rgba(255,255,255,.09);}
    .menu-page.fresatto-visual-menu .menu-grid .menu-item::before{content:"";position:absolute;inset:0;z-index:-2;background-image:var(--fresatto-dish-image);background-size:cover;background-position:center;opacity:.62;transform:scale(1.03);}
    .menu-page.fresatto-visual-menu .menu-grid .menu-item::after{content:"";position:absolute;inset:0;z-index:-1;background:linear-gradient(90deg,rgba(5,5,5,.98) 0%,rgba(5,5,5,.86) 40%,rgba(5,5,5,.42) 74%,rgba(5,5,5,.62) 100%),linear-gradient(180deg,rgba(5,5,5,.18) 0%,rgba(5,5,5,.08) 48%,rgba(5,5,5,.76) 100%);}
    .menu-page.fresatto-visual-menu .menu-grid .menu-item h3,.menu-page.fresatto-visual-menu .menu-grid .menu-item p,.menu-page.fresatto-visual-menu .menu-grid .menu-item .menu-price,.menu-page.fresatto-visual-menu .menu-grid .menu-item .menu-add{position:relative;z-index:2;}
    .menu-page.fresatto-visual-menu .menu-grid .menu-item p{color:#bdbdbd;}
    .menu-page.fresatto-visual-menu .menu-grid .menu-item .menu-add{box-shadow:0 10px 28px rgba(255,170,0,.16);}
    @media(max-width:600px){.menu-page.fresatto-visual-menu .menu-grid .menu-item{min-height:220px;}}
  `;document.head.appendChild(style);}
  function initBasePage(){if(typeof initRestaurantsPage==='function')initRestaurantsPage();if(typeof initMenuPage==='function')initMenuPage();if(typeof initOrderBuilderPage==='function')initOrderBuilderPage();if(typeof initHomeAdPopup==='function')initHomeAdPopup();if(typeof initTopBackLink==='function')initTopBackLink();initRestaurantsFallback();startClosedState();}
  function loadScript(src,onload){const script=document.createElement('script');script.src=src+(src.includes('?')?'&':'?')+'v='+ASSET_VERSION;script.onload=onload;script.onerror=()=>console.error(`No se pudo cargar ${src}`);document.head.appendChild(script);}
  function loadCatalogData(next){const needsCatalog=!!document.getElementById("menuGrid")||!!document.getElementById("orderRestaurantList");if(!needsCatalog){next();return;}loadScript("data/restaurants.js",()=>loadScript("data/fresatto-menu.js",next));}
  function loadConfiguratorStyles(){if(!document.getElementById("productConfiguratorStyles")){const link=document.createElement('link');link.id="productConfiguratorStyles";link.rel="stylesheet";link.href="css/product-configurator.css?v="+ASSET_VERSION;document.head.appendChild(link);}}
  function loadCustomScript(){loadConfiguratorStyles();loadFresattoVisualStyle();loadScript(CUSTOM_SCRIPT,()=>{loadScript(FIX_SCRIPT,()=>{const loadVisual=()=>{if(isFresattoMenu())window.loadFresattoMenuImages?.();initBasePage();setTimeout(()=>{window.loadFresattoMenuImages?.();initRestaurantsFallback();},250);};loadScript("js/fresatto-menu-images.js",loadVisual);});});}
  function loadBaseScript(){loadScript(BASE_SCRIPT,loadCustomScript);}
  loadCatalogData(loadBaseScript);
})();